# local development image built from this repository's Dockerfile
services:
  jekyll:
    image: fredolei/al-folio:local
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
